version: '3.8'
services:
  postgres:
    image: postgres
    container_name: postgres_JTQ
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=changeme
    ports:
      - "5432:5432"
    volumes:
      - postgres-volume:/var/lib/postgresql/data/
volumes:
  postgres-volume: